FROM node:lts-bookworm AS modules

WORKDIR /workspace

COPY ./package.json .

RUN npm i

FROM node:lts-bookworm

WORKDIR /workspace

COPY "*.config.js" "tsconfig.json" "package.json" ./
COPY --from=modules /workspace/node_modules ./node_modules

ENTRYPOINT ["npm", "run"]
CMD ["dev"]

