FROM node:16-alpine AS modules

WORKDIR /workspace

COPY ./package.json .

RUN npm i

FROM node:16-alpine

WORKDIR /workspace

COPY "*.config.js" "tsconfig.json" "package.json" .
COPY --from=modules /workspace/node_modules ./node_modules

ENTRYPOINT ["npm", "run"]
CMD ["dev"]

