version: "3"

services:
  node:
    build: ./node
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - CHOKIDAR_USEPOLLING=true
      - API_HOST=api
      - API_PORT=3000

  api:
    build: ./api
    environment:
      - PORT=3000
